# Generated by Django 2.0.1 on 2018-02-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180128_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='moblie',
            new_name='mobile',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='', max_length=50, verbose_name='email'),
        ),
    ]
