# Generated by Django 2.0.3 on 2018-04-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180228_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', 'register'), ('forget', 'forget'), ('update_email', 'update email')], max_length=10, verbose_name='sending type'),
        ),
    ]
