# Generated by Django 2.0.1 on 2018-01-23 20:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='course_name')),
                ('desc', models.CharField(max_length=300, verbose_name='course_describe')),
                ('details', models.TextField(verbose_name='course_detail')),
                ('degree', models.CharField(choices=[('cj', 'beginner'), ('zj', 'intermiddiate'), ('gj', 'advanced')], max_length=10, verbose_name='degree')),
                ('learn_time', models.IntegerField(default=0, verbose_name='learn_time')),
                ('student', models.IntegerField(default=0, verbose_name='student_numbers')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='fav_num')),
                ('image', models.ImageField(upload_to='course/%Y/%m', verbose_name='course_img')),
                ('click_num', models.IntegerField(default=0, verbose_name='click_num')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_name')),
            ],
            options={
                'verbose_name': 'courses',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='lesson_video')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_name')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='resourse file')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resource',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='lesson_name')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_name')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lesson',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='lesson_video')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_name')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='lesson')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'video',
            },
        ),
    ]
