# Generated by Django 2.0.1 on 2018-02-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='django development', max_length=200, verbose_name='course_category'),
        ),
    ]
