# Generated by Django 2.0.1 on 2018-02-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_time',
            field=models.IntegerField(default=0, verbose_name='lesson_time'),
        ),
    ]
