# Generated by Django 2.0.1 on 2018-01-23 20:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='city_name')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('desc', models.CharField(max_length=200, verbose_name='city_describe')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'city',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='org_name')),
                ('desc', models.TextField(verbose_name='org_describe')),
                ('click_nums', models.IntegerField(default=0, verbose_name='click_num')),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='course_img')),
                ('address', models.CharField(max_length=150, verbose_name='org_address')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='fav_num')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CityDict', verbose_name='org_city')),
            ],
            options={
                'verbose_name': 'course_org',
                'verbose_name_plural': 'course_org',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='teaher_name')),
                ('work_years', models.IntegerField(default=0, verbose_name='work_year')),
                ('work_company', models.CharField(max_length=50, verbose_name='work_company')),
                ('work_position', models.CharField(max_length=50, verbose_name='work_position')),
                ('features', models.CharField(max_length=50, verbose_name='teaching_features')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='fav_num')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='teacher_org')),
            ],
            options={
                'verbose_name': 'course_teacher',
                'verbose_name_plural': 'course_teacher',
            },
        ),
    ]
