# Generated by Django 2.0.1 on 2018-02-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('colledge', 'colledge'), ('private', 'private'), ('training orgs', 'training orgs')], default='colledge', max_length=20, verbose_name='org_category'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(upload_to='org/%Y/%m', verbose_name='course_logo'),
        ),
    ]
