# Generated by Django 2.0.3 on 2018-04-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='fav_num'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=18, verbose_name='age  '),
        ),
    ]
